chore(lint): bump linters

diff --git a/gcp-image-from-docker/builtin/expand-root b/gcp-image-from-docker/builtin/expand-root
--- a/gcp-image-from-docker/builtin/expand-root
+++ b/gcp-image-from-docker/builtin/expand-root
@@ -13,24 +13,24 @@ PARTITION="${2}"
 FILESYSTEM="${3}"
 
 if [[ -z "${DEVICE}" || -z "${PARTITION}" || -z "${FILESYSTEM}" ]]; then
-  echo "Requires: $0 DEVICE PARTITION FILESYSTEM"
-  exit 1
+    echo "Requires: $0 DEVICE PARTITION FILESYSTEM"
+    exit 1
 fi
 
 # Grow partition using growpart
 if [[ -x /usr/bin/growpart ]]; then
-  echo "Growing partition ${DEVICE}${PARTITION}"
-  /usr/bin/growpart "${DEVICE}" "${PARTITION}"
+    echo "Growing partition ${DEVICE}${PARTITION}"
+    /usr/bin/growpart "${DEVICE}" "${PARTITION}"
 else
-  echo "/usr/bin/growpart was not found"
-  exit 1
+    echo "/usr/bin/growpart was not found"
+    exit 1
 fi
 
 echo "Resizing ${FILESYSTEM} filesystem on ${DEVICE}${PARTITION}"
 case "${FILESYSTEM}" in
-  xfs)  xfs_growfs / ;;
-  ext2) resize2fs "${DEVICE}${PARTITION}" ;;
-  ext3) resize2fs "${DEVICE}${PARTITION}" ;;
-  ext4) resize2fs "${DEVICE}${PARTITION}" ;;
-  *) echo "Unsupported filesystem,  unable to expand size." ;;
+    xfs)  xfs_growfs / ;;
+    ext2) resize2fs "${DEVICE}${PARTITION}" ;;
+    ext3) resize2fs "${DEVICE}${PARTITION}" ;;
+    ext4) resize2fs "${DEVICE}${PARTITION}" ;;
+    *) echo "Unsupported filesystem,  unable to expand size." ;;
 esac
